// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdzBSQVMbrYGpUnBR8GM7bs4KaKSEg9M',
    appId: '1:1059817757211:web:9d587d096ec285708436be',
    messagingSenderId: '1059817757211',
    projectId: 'moologue',
    authDomain: 'moologue.firebaseapp.com',
    databaseURL: 'https://moologue-default-rtdb.firebaseio.com',
    storageBucket: 'moologue.firebasestorage.app',
    measurementId: 'G-TPQEJSSPKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyA0a4QMh58us0P_DGei-_qWvAZCkNKmI',
    appId: '1:1059817757211:android:15c9e18356f1d4df8436be',
    messagingSenderId: '1059817757211',
    projectId: 'moologue',
    databaseURL: 'https://moologue-default-rtdb.firebaseio.com',
    storageBucket: 'moologue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGk0X-94vp3z4oa_B2hs_OUpV9c1DHrE',
    appId: '1:1059817757211:ios:cdafec87aec5f2db8436be',
    messagingSenderId: '1059817757211',
    projectId: 'moologue',
    databaseURL: 'https://moologue-default-rtdb.firebaseio.com',
    storageBucket: 'moologue.firebasestorage.app',
    androidClientId: '1059817757211-0jgar4bv3382ont4qgn3s7q5d0ppbjak.apps.googleusercontent.com',
    iosClientId: '1059817757211-pi2clb5rsfnj6itiqsiuq1auef7tuq2p.apps.googleusercontent.com',
    iosBundleId: 'com.mooanalytica.moologue',
  );
}
